#!/usr/bin/env python
"""Unified tier-driven TAPP generator (schema + shared catalogs + vocab + detail BB).

ONE generator for the tier-column workbooks, replacing the per-technique
build_{laicpms,labxct}_from_spreadsheet.py scripts. Routing follows the canonical
Protocol-Level x Analysis-Level matrix (docs/TierImplementationPatterns.xlsx):

  Basic protocol    -> required top-level ada: property (…Default if editable at analysis)
  Advanced protocol -> schema:additionalProperty[] PropertyValueSpecification
                       (…Default name + readonlyValue:false when dual-homed; bare + readonly:true if Read-Only)
  Analysis Basic    -> required top-level ada: property in the detail BB
  Analysis Editable/Advanced -> optional schema:additionalProperty PropertyValue in the detail BB
  Analysis Read-Only / N/A   -> absent from the detail
  Basic fields no publication reports (coverage 0) -> optional (not required)

Analyte-specific rows are identified by the per-TAPP analyte_map (impl-notes-derived) and
reference the shared analyteColumns registry. Usage:

    python tools/build_tapp.py <tapp_name>      # e.g. laicpmsTAPP, labxctTAPP

Run tools/build_tapp_examples.py afterwards to (re)build the publication / synthetic examples.
(empaTAPP is still generated by _tapp_lib.py — Stage 2 of the consolidation.)
"""
import json, os, re, sys
import openpyxl
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TP = os.path.join(ROOT, "_sources", "techniqueProtocols")
VOCAB_DIR = os.path.join(TP, "vocab")
PT = os.path.join(TP, "parameterTemplates", "schema.yaml")
PV = os.path.join(TP, "parameterValues", "schema.yaml")
CTX = {"schema": "http://schema.org/", "ada": "https://ada.astromat.org/metadata/"}

# Analyte-specific rows -> existing analyteColumns $def names (reused, not regenerated).
LAICPMS_ANALYTE_MAP = {
    "Spectrometer Dwell Time": ["spectrometerDwellTime"],
    "Detection Limit": ["detectionLimit"],
    "Detection Limit Method": ["detectionLimitMethod"],
    "Limit of Quantification (LOQ) Method": ["limitOfQuantification"],
    "Within-Session Analytical Precision and Assessment Method":
        ["withinSessionReproducibility", "withinSessionReproducibilityMethod"],
    "Between-Session (Long-Term) Analytical Precision and Assessment Method":
        ["betweenSessionReproducibility", "betweenSessionReproducibilityMethod"],
    "Analytical Accuracy and Assessment Method": ["analyticalAccuracy", "analyticalAccuracyMethod"],
    "Interfering Species": ["interferingSpecies"],
    "Interference Correction Method": ["IsobaricInterferenceCorrectionMethod"],
    "Isobaric Interference Corrections Applied": ["IsobaricInterferenceCorrection"],
}
_IDENTITY_COMMON = {"Protocol Name", "Technique", "Protocol Author", "Laboratory",
                    "Protocol Start Date", "Funding Source for Protocol Development",
                    "Target Material", "Protocol Reference(s)", "Protocol DOI", "Laboratory ID"}

TAPP_CONFIGS = {
    "empaTAPP": {
        # Evolved-past prototype workbook, routed by the canonical matrix +
        # `schema path` roles (see route_empa/build_empa). Titles/descriptions and
        # the rich emitters come from _tapp_lib (TAPP_PROFILES['empaTAPP']).
        "xlsx": "docs/TAPP_EPMA_filled-noInterp.xlsx",
        "prefix": "empa",
        "mode": "empa",
    },
    "laicpmsTAPP": {
        "xlsx": "docs/LA-Q_SF-ICPMS_TAPP_v2.xlsx",
        "prefix": "laicpms",
        "component_types": ["ada:LAICPMSTabular", "ada:LAICPMSMap", "ada:LAICPMSImage", "ada:LAICPMSTransect"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": LAICPMS_ANALYTE_MAP,
        "conditional_mode": "Mapping",
        "enum_props": {},
        "title": "LA-ICPMS Technique-Aligned Protocol Profile (laicpmsTAPP)",
        "description": ("LA-ICP-MS (incl. LA-Q-ICP-MS and LA-SF-ICP-MS) extension of the base TAPP "
                        "definition. Basic protocol-tier fields are required top-level ada: properties; "
                        "Advanced protocol-tier fields are schema:additionalProperty[] "
                        "PropertyValueSpecification entries; an ada:analyteTemplate carries the "
                        "per-element columns. Generated from docs/LA-Q_SF-ICPMS_TAPP_v2.xlsx by "
                        "tools/build_tapp.py."),
        "detail_title": "LA-ICPMS Analysis Detail",
        "detail_description": ("Detail block for LA-ICP-MS hasPart items. Discriminates on "
                               "ada:componentType, carries analysis-level required properties and an "
                               "@id reference to a registered laicpmsTAPP definition, and per-dataset "
                               "schema:additionalProperty entries constrained via $refs to the "
                               "parameterValues registry plus a catch-all. Generated by tools/build_tapp.py."),
    },
    "labxctTAPP": {
        "xlsx": "docs/Lab-XCT_TAPP_v8.xlsx",
        "prefix": "labxct",
        "component_types": ["ada:XCTVolume", "ada:XCTProjectionImageSet", "ada:XCTSegmentationVolume",
                            "ada:XCTRenderedImage", "ada:XCTQuantitativeTabular"],
        "base_items": _IDENTITY_COMMON | {"CT System Manufacturer and Model"},
        "analyte_map": {},
        "conditional_mode": "Multi-volume stitching",
        "enum_props": {"analyticalMode": ["Single-volume", "Multi-volume stitching",
                                          "Single-volume; Multi-volume stitching"]},
        "title": "Lab-XCT Technique-Aligned Protocol Profile (labxctTAPP)",
        "description": ("Laboratory X-ray computed tomography (polychromatic cone-beam) extension of "
                        "the base TAPP definition. Basic protocol-tier fields are required top-level "
                        "ada: properties; Advanced protocol-tier fields are schema:additionalProperty[] "
                        "PropertyValueSpecification entries. XCT has no per-element analyte axis, so no "
                        "ada:analyteTemplate is defined. Generated from docs/Lab-XCT_TAPP_v8.xlsx by "
                        "tools/build_tapp.py."),
        "detail_title": "Lab-XCT Analysis Detail",
        "detail_description": ("Detail block for Lab-XCT hasPart items. Discriminates on "
                               "ada:componentType, carries analysis-level required properties and an "
                               "@id reference to a registered labxctTAPP definition, and per-dataset "
                               "schema:additionalProperty entries constrained via $refs to the "
                               "parameterValues registry plus a catch-all. Generated by tools/build_tapp.py."),
    },
}

CFG = {}
TAPP = PARAM_BASE = VOCAB_BASE = TAPP_DIR = DETAIL_DIR = XLSX = None


def configure(tapp_name):
    global CFG, TAPP, PARAM_BASE, VOCAB_BASE, TAPP_DIR, DETAIL_DIR, XLSX
    if tapp_name not in TAPP_CONFIGS:
        raise SystemExit(f"Unknown TAPP {tapp_name!r}. Known: {sorted(TAPP_CONFIGS)}")
    CFG = TAPP_CONFIGS[tapp_name]
    TAPP = tapp_name
    PARAM_BASE = "ada:parameter/" + TAPP
    VOCAB_BASE = "ada:vocab/" + TAPP
    TAPP_DIR = os.path.join(TP, TAPP)
    short = TAPP.replace("TAPP", "").upper()
    DETAIL_DIR = os.path.join(ROOT, "_sources", "analysisSpecificDetails", "detail" + short)
    XLSX = os.path.join(ROOT, *CFG["xlsx"].split("/"))


# ---------- small helpers ----------
def norm(v):
    return " ".join(str(v).split()) if v is not None else ""


def camel(s):
    s = re.sub(r"\(.*?\)", "", s)
    s = re.sub(r"[^A-Za-z0-9 ]", " ", s).strip()
    parts = s.split()
    return (parts[0].lower() + "".join(p.capitalize() for p in parts[1:])) if parts else "x"


def jtype(dt):
    d = dt.lower()
    if "integer" in d:
        return "integer"
    if "numeric" in d or "number" in d:
        return "number"
    if "boolean" in d:
        return "boolean"
    if d.startswith("date"):
        return "date"
    if "uri" in d or "doi" in d:
        return "uri"
    return "string"


def unit(dt):
    m = re.search(r"\(([^)]+)\)", dt)
    return m.group(1) if m else None


def meaningful(v):
    v = re.sub(r"\s*\[P[^\]]*\]", "", norm(v)).strip()
    if v in ("", "N", "N/A"):
        return False
    m = re.match(r"^(N/A|N)\b\s*", v)
    if m:
        rest = v[m.end():]
        if rest.startswith("("):
            depth = 0
            for i, ch in enumerate(rest):
                depth += (ch == "(") - (ch == ")")
                if ch == ")" and depth == 0:
                    rest = rest[i + 1:]
                    break
        if re.fullmatch(r"[/;,\-\s]*", rest.strip()):
            return False
    return True


def dump_yaml(obj):
    return yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, default_flow_style=False, width=100)


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def def_key(bare, existing):
    return (CFG["prefix"] + "_" + bare) if bare in existing else bare


def is_dual(b):
    return b["A"] in ("Basic", "Editable", "Advanced")


def methoddef_name(b):
    return b["name"] + ("Default" if is_dual(b) else "")


def param_template_def(b, existing):
    mdname = methoddef_name(b)
    name = def_key(mdname, existing)
    props = {
        "@id": {"const": PARAM_BASE + "/" + mdname},
        "@type": {"const": ["schema:PropertyValueSpecification"]},
        "schema:valueName": {"const": mdname},
        "schema:name": {"const": b["item"]},
        "ada:dataType": {"const": b["jtype"]},
        "ada:fieldScope": {"const": "session"},
        "schema:readonlyValue": {"const": not is_dual(b)},
        "ada:tier": {"const": "R"},
    }
    if b.get("unit") and b["unit"] != "free":
        props["schema:unitText"] = {"const": b["unit"]}
    return name, {name: {"title": b["item"], "description": b["desc"], "type": "object",
                         "properties": props,
                         "required": ["@id", "@type", "schema:valueName", "schema:name",
                                      "ada:dataType", "ada:fieldScope"]}}


def param_value_def(b, existing):
    bare = b["name"]
    name = def_key(bare, existing)
    has_unit = bool(b.get("unit") and b["unit"] != "free")
    props = {
        "@id": {"const": PARAM_BASE + "/" + bare},
        "@type": {"const": ["schema:PropertyValue"]},
        "schema:propertyID": {"const": PARAM_BASE + "/" + bare},
        "schema:name": {"const": b["item"]},
    }
    props["schema:value"] = ({"anyOf": [{"type": "number"}, {"type": "string"}]}
                             if b["jtype"] in ("number", "integer") else {"type": "string"})
    req = ["@id", "@type", "schema:propertyID", "schema:name", "schema:value"]
    if has_unit:
        props["schema:unitText"] = {"type": "string"}
        req.append("schema:unitText")
    return name, {name: {"title": b["item"], "description": b["desc"], "type": "object",
                         "properties": props, "required": req}}


def remove_owned_blocks(path, owner_substr):
    """Drop $def blocks whose body references owner_substr (this TAPP's @id), preserving
    formatting of other entries. Idempotent regen (remove before re-append)."""
    lines = open(path, encoding="utf-8").read().splitlines(keepends=True)
    out, i, removed = [], 0, []
    defs_re = re.compile(r"^  (\S.*):\s*$")
    while i < len(lines):
        m = defs_re.match(lines[i])
        if m:
            j = i + 1
            block = [lines[i]]
            while j < len(lines) and not defs_re.match(lines[j]):
                block.append(lines[j]); j += 1
            (removed.append(m.group(1)) if owner_substr in "".join(block) else out.extend(block))
            i = j
        else:
            out.append(lines[i]); i += 1
    open(path, "w", encoding="utf-8", newline="\n").write("".join(out))
    return removed


def append_defs(catalog_path, defs):
    frag = ""
    for name, body in defs.items():
        block = dump_yaml({name: body})
        frag += "\n" + "\n".join(("  " + ln) if ln else ln for ln in block.splitlines())
    with open(catalog_path, "a", encoding="utf-8", newline="\n") as f:
        f.write(frag.rstrip("\n") + "\n")
    print("appended", len(defs), "$defs to", os.path.relpath(catalog_path, ROOT))


def existing_keys(path):
    d = yaml.safe_load(open(path, encoding="utf-8")) or {}
    return set((d.get("$defs") or {}).keys())


def write_vocab(b):
    terms = [{"@type": ["schema:DefinedTerm"], "schema:termCode": t, "schema:name": t}
             for t in b["terms"] if t not in ("N/A", "None")]
    obj = {
        "$schema": "https://cross-domain-interoperability-framework.github.io/metadataBuildingBlocks/_sources/schemaorgProperties/definedTermSet/schema.yaml",
        "@context": CTX, "@id": VOCAB_BASE + "/" + b["name"], "@type": ["schema:DefinedTermSet"],
        "schema:name": b["item"], "schema:description": b["desc"][:300],
        "schema:hasDefinedTerm": terms,
    }
    write(os.path.join(VOCAB_DIR, CFG["prefix"] + "_" + b["name"] + ".json"),
          json.dumps(obj, indent=2, ensure_ascii=False) + "\n")


# ---------- routing ----------
def route():
    ws = openpyxl.load_workbook(XLSX, data_only=True, read_only=True)["TAPP"]
    rows = list(ws.iter_rows(min_row=1, values_only=True))
    hdr = rows[0]
    lit = [i for i, v in enumerate(hdr) if norm(v).lower() == "literature assessment"][0]
    R = {"tapp_prop": [], "method_param": [], "detail_req": [], "detail_addl": [],
         "analyte_cols": [], "vocab": []}
    amap = CFG["analyte_map"]
    for r in rows[1:]:
        item = norm(r[0])
        if not item or re.match(r"^\d+\.\s", item):
            continue
        P, A, dt, ex = norm(r[2]), norm(r[3]), norm(r[4]), norm(r[5])
        modes = [norm(hdr[i]) for i in range(8, lit) if norm(r[i]) in ("Y", "y")]
        cov = sum(1 for i in range(lit + 1, len(r)) if meaningful(r[i]))
        rec = {"item": item, "name": camel(item), "P": P, "A": A, "jtype": jtype(dt),
               "unit": unit(dt), "desc": norm(r[1]), "allowed": ex, "cov": cov,
               "multivol_only": (modes == [CFG["conditional_mode"]])}
        if item in amap:
            R["analyte_cols"].append({**rec, "cols": amap[item]})
            continue
        if item in CFG["base_items"]:
            continue
        if "controlled" in dt.lower() or dt.lower().startswith("boolean"):
            terms = (["Yes", "No"] if dt.lower().startswith("boolean")
                     else [p.strip().strip("'\"") for p in ex.split("|")
                           if p.strip() and not p.strip().lower().startswith("e.g")
                           and "specify" not in p.strip().lower()])
            if terms:
                R["vocab"].append({**rec, "terms": terms})
        if P == "Basic":
            R["tapp_prop"].append(rec)
        elif P == "Advanced":
            R["method_param"].append(rec)
        if A == "Basic":
            R["detail_req"].append(rec)
        elif A in ("Editable", "Advanced"):
            R["detail_addl"].append(rec)
    return R


# ---------- build ----------
def build():
    os.makedirs(DETAIL_DIR, exist_ok=True)
    R = route()
    for b in R["vocab"]:
        write_vocab(b)

    remove_owned_blocks(PT, PARAM_BASE + "/")
    remove_owned_blocks(PV, PARAM_BASE + "/")
    pt_existing, pv_existing = existing_keys(PT), existing_keys(PV)

    pt_defs, pt_keys = {}, []
    for b in R["method_param"]:
        n, d = param_template_def(b, pt_existing); pt_defs.update(d); pt_keys.append(n); pt_existing.add(n)
    append_defs(PT, pt_defs)

    pv_defs, pv_keys, pv_ids, seen = {}, [], [], set()
    for b in R["detail_addl"]:
        if b["name"] in seen:
            continue
        seen.add(b["name"])
        n, d = param_value_def(b, pv_existing); pv_defs.update(d); pv_keys.append(n)
        pv_ids.append(PARAM_BASE + "/" + b["name"]); pv_existing.add(n)
    append_defs(PV, pv_defs)

    acols = []
    for b in R["analyte_cols"]:
        for c in b["cols"]:
            if c not in acols:
                acols.append(c)

    # ---- TAPP schema ----
    tapp_props, basic_required = {}, []
    enum_props = CFG["enum_props"]
    for b in R["tapp_prop"]:
        key = "ada:" + b["name"] + ("Default" if b["A"] == "Editable" else "")
        if b["name"] in enum_props:
            tapp_props[key] = {"description": b["desc"], "type": "string", "enum": list(enum_props[b["name"]])}
        elif b["jtype"] in ("number", "integer"):
            tapp_props[key] = {"description": b["desc"], "anyOf": [{"type": "number"}, {"type": "string"}]}
        else:
            tapp_props[key] = {"description": b["desc"], "type": "string"}
        if b["cov"] > 0:
            basic_required.append(key)
    if acols:
        ac_refs = [{"$ref": "../tappDefinition/schema.yaml#/$defs/AnalyteIdentifierColumn"}] + \
                  [{"$ref": "../analyteColumns/schema.yaml#/$defs/" + c} for c in acols]
        ac_contains = [{"contains": {"$ref": "../analyteColumns/schema.yaml#/$defs/" + c},
                        "minContains": 0, "maxContains": 1} for c in acols]
        tapp_props["ada:analyteTemplate"] = {"type": "object", "properties": {
            "ada:analyteColumns": {"type": "array", "items": {"anyOf": ac_refs}, "allOf": ac_contains}}}
    sap_refs = [{"$ref": "../parameterTemplates/schema.yaml#/$defs/" + n} for n in pt_keys]
    sap_contains = [{"contains": {"$ref": "../parameterTemplates/schema.yaml#/$defs/" + n},
                     "minContains": 0, "maxContains": 1} for n in pt_keys]
    tapp_props["schema:additionalProperty"] = {
        "type": "array",
        "description": ("Method-level parameter specifications (Advanced protocol tier). Each entry is "
                        "a schema:PropertyValueSpecification; dual-homed fields use the …Default name "
                        "here and carry the per-dataset value in the detail block."),
        "items": {"anyOf": sap_refs}, "allOf": sap_contains}
    tapp_schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": CFG["title"], "description": CFG["description"],
        "allOf": [{"$ref": "../tappDefinition/schema.yaml"},
                  {"type": "object", "properties": tapp_props, "required": basic_required}]}
    write(os.path.join(TAPP_DIR, "schema.yaml"), dump_yaml(tapp_schema))

    # ---- detail schema ----
    req = ["ada:componentType"]
    block1 = {
        "ada:componentType": {"anyOf": [{"const": c} for c in CFG["component_types"]]},
        "schema:measurementTechnique": {"type": "object",
            "description": f"@id reference to a registered {TAPP} TAPP definition.",
            "properties": {"@id": {"type": "string", "format": "uri"}}, "required": ["@id"]}}
    for b in R["detail_req"]:
        key = "ada:" + b["name"]
        block1[key] = {"description": b["desc"],
                       "type": "string" if b["jtype"] in ("string", "date", "uri") else b["jtype"]}
        if not b["multivol_only"]:
            req.append(key)
    pv_branches = [{"$ref": "../../techniqueProtocols/parameterValues/schema.yaml#/$defs/" + n} for n in pv_keys]
    catchall = {"type": "object",
        "description": f"Catch-all for additional schema:PropertyValue entries beyond the {TAPP}-derived catalog.",
        "properties": {"@type": {"type": "array", "items": {"type": "string"},
                                 "contains": {"const": "schema:PropertyValue"}},
                       "schema:propertyID": {"type": "string", "not": {"enum": pv_ids}}},
        "required": ["@type", "schema:propertyID"]}
    detail = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": CFG["detail_title"], "description": CFG["detail_description"],
        "allOf": [{"type": "object", "properties": block1, "required": req},
                  {"type": "object", "properties": {"schema:additionalProperty": {
                      "type": "array", "description": "Per-dataset schema:PropertyValue entries. All optional.",
                      "items": {"anyOf": pv_branches + [catchall]}}}}]}
    write(os.path.join(DETAIL_DIR, "schema.yaml"), dump_yaml(detail))

    json.dump({"tapp_props": list(tapp_props.keys()), "pt_keys": pt_keys, "pv_keys": pv_keys,
               "analyte_cols": acols, "detail_req": [b["name"] for b in R["detail_req"]],
               "detail_req_multivol": [b["name"] for b in R["detail_req"] if b["multivol_only"]],
               "component_types": CFG["component_types"], "basic_required": basic_required,
               "basic_props": [{"key": "ada:" + b["name"] + ("Default" if b["A"] == "Editable" else ""),
                                "item": b["item"], "jtype": b["jtype"], "cov": b["cov"],
                                "required": b["cov"] > 0} for b in R["tapp_prop"]]},
              open(os.path.join(ROOT, "docs", "new_tapps202606", CFG["prefix"] + "_gen_index.json"), "w"), indent=1)
    print(f"DONE {TAPP}: tapp_prop={len(R['tapp_prop'])} method_param={len(pt_keys)} "
          f"detail_req={len(R['detail_req'])} detail_addl={len(pv_keys)} analyteCols={len(acols)} vocab={len(R['vocab'])}")


# ---------- empaTAPP: schema-path + matrix routing over the _tapp_lib reader/emitters ----------
# empaTAPP is the evolved-past prototype workbook. Rather than bend the generic
# generator to its quirks, it is routed by the SAME canonical matrix as the other
# TAPPs (Protocol/Analysis tier columns) with the `schema path` column resolving
# the special roles (analyteColumn / analyte-identifier / schema:description /
# inherited base field / instrument). The rich emitters + registry writers +
# rich per-pub example builder live in _tapp_lib and are reused as a library;
# only the routing brain is build_tapp's (matrix), retiring _tapp_lib's old
# impl-tag-kind routing for empa.

_TIER_NORM = {"basic": "Basic", "editable": "Editable", "advanced": "Advanced",
              "read-only": "Read-Only", "readonly": "Read-Only", "read only": "Read-Only",
              "n/a": "N/A", "na": "N/A", "": ""}


def _norm_tier(v):
    return _TIER_NORM.get((v or "").strip().lower(), (v or "").strip())


def _empa_role(sp):
    """Resolve a row's structural role from its `schema path` value."""
    s = sp or ""
    if "ada:analyteTemplate.ada:analyteColumns" in s:
        return "analyteColumn"
    if "ada:analyteTemplate.ada:defaultAnalytes" in s:
        return "analyteIdentifier"
    if "schema:description" in s and "methodParameters" not in s:
        return "description"
    if s.startswith("$MethodDefinition") and "ada:" not in s:
        return "inherited"            # identity / instrument / inherited base field
    return "field"                    # regular property-or-parameter (matrix decides home)


_CLEAN_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")


def _empa_base_name(row):
    """Base property/parameter name: clean ada:<name> segment of the schema path
    (Default suffix stripped), else the impl-notes tag name, else camelCase(item)."""
    sp = row.get("schema_path") or ""
    if "ada:" in sp and "methodParameters" not in sp and "analyteTemplate" not in sp:
        seg = sp.split("ada:")[-1].strip()
        if _CLEAN_NAME.match(seg):
            return re.sub(r"Default$", "", seg)
    tags = (row.get("parsed") or {}).get("tags") or []
    if tags:
        return tags[0][1]
    return camel(row["item"])


def route_empa(rows, L):
    """Matrix + schema-path routing for empaTAPP, producing the classification
    structures consumed by _tapp_lib's build_schema_yaml / registry writers."""
    # --- vocab dedup by sorted enum tuple (mirrors _tapp_lib._classify_rows) ---
    enum_to_vocab = {}
    for row in rows:
        enum = (row.get("parsed") or {}).get("enum")
        if not enum:
            continue
        key = tuple(sorted(enum))
        if key in enum_to_vocab:
            continue
        # Vocab name mirrors _tapp_lib._classify_rows: first impl tag name, else the
        # slugified item (case preserved — do NOT camelCase, so e.g. "Technique"
        # stays "Technique", matching the existing shared vocab file).
        tags = (row.get("parsed") or {}).get("tags") or []
        name = tags[0][1] if tags else re.sub(r"[^A-Za-z0-9]+", "_", row["item"]).strip("_")
        enum_to_vocab[key] = name
        L.share_or_write_catalog(L.VOCAB_DIR / f"{name}.json",
                                 L.vocab_obj(name, row["item"] or name, row.get("desc") or "", enum))

    def vocab_for(enum):
        return enum_to_vocab.get(tuple(sorted(enum))) if enum else None

    schema_properties, required_props = [], []
    by_item = {}  # item -> placement record for the example builder
    analyte_column_names, parameter_names, detail_param_names = [], [], []
    analyte_column_defs = __import__("collections").OrderedDict()
    parameter_template_defs = __import__("collections").OrderedDict()
    param_value_defs = __import__("collections").OrderedDict()
    seen_pv = set()

    for row in rows:
        item = row.get("item")
        if not item or re.match(r"^\d+\.\s", item):
            continue
        role = _empa_role(row.get("schema_path"))
        if role in ("inherited", "analyteIdentifier", "description"):
            continue  # handled by the base TAPP / instrument constraint / example builder
        P = _norm_tier(row.get("P"))
        A = _norm_tier(row.get("A"))
        parsed = row.get("parsed") or {}
        enum = parsed.get("enum")
        dtype = parsed.get("dtype") or row.get("dtype_col")
        jt = L.map_dtype(dtype)
        vname = vocab_for(enum)
        name = _empa_base_name(row)
        ro = parsed.get("readOnly")

        if role == "analyteColumn":
            analyte_column_names.append(name)
            analyte_column_defs[name] = L.analyte_column_obj(
                name, item, row.get("desc") or "", dtype, vname,
                ro if ro is not None else (A == "Read-Only"))
            continue

        # regular field — matrix decides the home(s)
        dual = A in ("Basic", "Editable", "Advanced")
        rec = {"role": "field", "P": P, "A": A, "name": name, "dual": dual,
               "enum": list(enum) if enum else None, "dtype": dtype,
               "detail": A in ("Editable", "Advanced")}
        if P == "Basic":
            key = "ada:" + name + ("Default" if A == "Editable" else "")
            rec["tapp_key"] = key
            if enum:
                block = {"description": row.get("desc") or "", "type": "string", "enum": list(enum)}
            elif jt in ("number", "integer"):
                block = {"description": row.get("desc") or "",
                         "anyOf": [{"type": "number"}, {"type": "string"}]}
            elif jt == "boolean":
                block = {"description": row.get("desc") or "", "type": "boolean"}
            else:
                block = {"description": row.get("desc") or "", "type": "string"}
            schema_properties.append((key, block))
            cov = sum(1 for v in (row.get("pubs") or []) if L._pub_meaningful(v))
            if cov > 0:
                required_props.append(key)
        elif P == "Advanced":
            mdname = name + ("Default" if dual else "")
            rec["mdname"] = mdname
            parameter_names.append(mdname)
            parameter_template_defs[mdname] = L.parameter_obj(
                mdname, item, row.get("desc") or "", dtype, vname, not dual)
        by_item[item] = rec

        # detail side (per-dataset value) — Analysis Editable/Advanced
        if A in ("Editable", "Advanced") and name not in seen_pv:
            seen_pv.add(name)
            detail_param_names.append(name)
            param_value_defs[name] = L.additional_property_obj(
                name, item, row.get("desc") or "", row.get("dtype_col"), vname, dtype)

    # dedupe schema_properties (last wins)
    seen = {}
    for k, b in schema_properties:
        seen[k] = b
    schema_properties = list(seen.items())
    required_props = [k for k in dict.fromkeys(required_props) if k in seen]

    return {
        "schema_properties": schema_properties, "required_props": required_props,
        "analyte_column_names": analyte_column_names, "analyte_column_defs": analyte_column_defs,
        "parameter_names": parameter_names, "parameter_template_defs": parameter_template_defs,
        "detail_param_names": detail_param_names, "param_value_defs": param_value_defs,
        "by_item": by_item,
    }


def _regen_detail_addl_constraint(L, detail_param_names):
    """Rewrite ONLY detailEMPA/schema.yaml allOf[1] (the schema:additionalProperty
    constraint) to reference the current parameterValues $defs + catch-all,
    preserving the hand-authored allOf[0]."""
    from ruamel.yaml import YAML
    sp = L.DETAIL_EMPA / "schema.yaml"
    if not sp.exists():
        return
    y = YAML()
    y.preserve_quotes = True
    y.width = 4096
    y.indent(mapping=2, sequence=4, offset=2)
    doc = y.load(open(sp, encoding="utf-8"))
    names = sorted(detail_param_names)
    pvbase = "../../techniqueProtocols/parameterValues/schema.yaml#/$defs/"
    anyof = [{"$ref": pvbase + n} for n in names]
    anyof.append({
        "type": "object",
        "description": ("Catch-all for additional schema:PropertyValue entries beyond those "
                        "enumerated in the empaTAPP-derived catalog above."),
        "properties": {
            "@type": {"type": "array", "items": {"type": "string"},
                      "contains": {"const": "schema:PropertyValue"}},
            "schema:propertyID": {"type": "string",
                                  "not": {"enum": [f"ada:parameter/empaTAPP/{n}" for n in names]}},
        },
        "required": ["@type", "schema:propertyID"],
    })
    block1 = {"type": "object", "properties": {"schema:additionalProperty": {
        "type": "array",
        "description": ("Per-dataset schema:PropertyValue entries for this EMPA dataset. Each item "
                        "is any of the empaTAPP-derived parameter types or (via the catch-all "
                        "branch) any other PropertyValue. All entries are optional — include only "
                        "the parameters you have values for."),
        "items": {"anyOf": anyof}}}}
    doc["allOf"][1] = L._to_commented(block1)
    with open(sp, "w", encoding="utf-8") as f:
        y.dump(doc, f)
    print(f"  rewrote detailEMPA allOf[1] additionalProperty constraint ({len(names)} PV refs)")


def build_empa():
    """Generate empaTAPP via the canonical matrix router + _tapp_lib emitters.
    Reuses _tapp_lib for the rich emitters, registry writers, instrument hasPart
    constraint, and (hand-authored) detail schema preservation."""
    import _tapp_lib as L
    L.CATALOG_CONFLICTS.clear()
    L.configure("empaTAPP", os.path.relpath(XLSX, ROOT))
    rows = L.read_rows()
    print(f"empaTAPP: read {len(rows)} rows from {os.path.relpath(XLSX, ROOT)}")
    cls = route_empa(rows, L)

    instrument = L.build_haspart_constraint(rows)
    L.build_schema_yaml(cls["schema_properties"], cls["analyte_column_names"],
                        cls["parameter_names"], instrument, required_props=cls["required_props"])
    L.write_analyte_columns_registry(cls["analyte_column_defs"])
    L.write_parameter_templates_registry(cls["parameter_template_defs"])
    L.write_parameter_values_registry(cls["param_value_defs"])
    # detailEMPA/schema.yaml: allOf[0] is hand-authored (ada:spectrometersUsed,
    # ada:signalUsed, componentType enum, measurementTechnique) and preserved.
    # Only allOf[1] (the schema:additionalProperty constraint) is regenerated to
    # track the current detail PV set (one $ref per readOnly:false parameter + catch-all).
    _regen_detail_addl_constraint(L, cls["detail_param_names"])

    # ---- per-publication examples (matrix-routed via route_map) ----
    prop_type = {}
    for k, b in cls["schema_properties"]:
        prop_type[k] = ("number" if "anyOf" in b else b.get("type", "string"))
    req_set = set(cls["required_props"])
    rmap = cls["by_item"]
    examples_yaml = []
    n_tapp = n_detail = 0
    for i, (pcode, plabel) in enumerate(L._pubs()):
        empa_ex, detail_ex = L.example_for_pub(i, plabel, rows, route_map=rmap)
        for key, _b in cls["schema_properties"]:
            present = key in empa_ex
            ok = present and L._pub_meaningful(empa_ex[key])
            if key in req_set:
                if not ok:
                    empa_ex[key] = (-9999 if prop_type.get(key) == "number" else "missing")
            elif present and not ok:
                del empa_ex[key]
        L.write_json(L.BB / f"exampleempaTAPP-{pcode}.json", empa_ex)
        n_tapp += 1
        examples_yaml.append((pcode, plabel))
        if detail_ex.get("schema:additionalProperty"):
            L.write_json(L.DETAIL_EMPA / f"exampledetailEMPA-{pcode}.json", detail_ex)
            n_detail += 1
    L._write_examples_yaml(examples_yaml)
    print(f"  wrote {n_tapp} empaTAPP + {n_detail} detailEMPA examples")

    json.dump({"schema_properties": [k for k, _ in cls["schema_properties"]],
               "required_props": cls["required_props"],
               "analyte_column_names": sorted(cls["analyte_column_names"]),
               "parameter_names": sorted(cls["parameter_names"]),
               "detail_param_names": sorted(cls["detail_param_names"]),
               "basic_props": [{"key": k, "required": k in set(cls["required_props"])}
                               for k, _ in cls["schema_properties"]]},
              open(os.path.join(ROOT, "docs", "new_tapps202606", "empa_gen_index.json"), "w"), indent=1)
    print(f"DONE empaTAPP: props={len(cls['schema_properties'])} "
          f"(required {len(cls['required_props'])}) params={len(cls['parameter_names'])} "
          f"analyteCols={len(cls['analyte_column_names'])} detailValues={len(cls['detail_param_names'])}")
    if L.CATALOG_CONFLICTS:
        print(f"  {len(L.CATALOG_CONFLICTS)} catalog conflict(s) — see warnings above.")


def main():
    if len(sys.argv) < 2:
        raise SystemExit(f"usage: build_tapp.py <tapp_name>   known: {sorted(TAPP_CONFIGS)}")
    configure(sys.argv[1])
    if CFG.get("mode") == "empa":
        build_empa()
    else:
        build()


if __name__ == "__main__":
    main()
