#!/usr/bin/env python
"""Unified tier-driven TAPP generator (schema + shared catalogs + vocab + detail BB).

ONE generator for the tier-column workbooks, replacing the per-technique
build_{laicpms,labxct}_from_spreadsheet.py scripts. Routing follows the canonical
Protocol-Level x Analysis-Level matrix (docs/TierImplementationPatterns.xlsx):

  Basic protocol    -> required top-level ada: property (…Default if editable at analysis)
  Advanced protocol -> schema:additionalProperty[] PropertyValueSpecification
                       (…Default name + readonlyValue:false when dual-homed; bare + readonly:true if Read-Only)
  Analysis Basic    -> required top-level ada: property in the detail BB
  Analysis Editable/Advanced -> optional schema:additionalProperty PropertyValue in the detail BB
  Analysis Read-Only / N/A   -> absent from the detail
  Basic fields no publication reports (coverage 0) -> optional (not required)

Analyte-specific rows are identified by the per-TAPP analyte_map (impl-notes-derived) and
reference the shared analyteColumns registry. Usage:

    python tools/build_tapp.py <tapp_name>      # e.g. laicpmsTAPP, labxctTAPP

Run tools/build_tapp_examples.py afterwards to (re)build the publication / synthetic examples.
(empaTAPP is still generated by _tapp_lib.py — Stage 2 of the consolidation.)
"""
import json, os, re, sys
import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tapp_source

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# group-by-technique layout: registry/ (catalogs+vocab), BaseSchema/ (tappDefinition+adaProduct+
# geochemProperties), techniqueProfile/<tech>/{tapp,detail,profile,profile-ada}.
REG = os.path.join(ROOT, "_sources", "registry")
TPROF = os.path.join(ROOT, "_sources", "techniqueProfile", "geochemProfile")
VOCAB_DIR = os.path.join(REG, "vocab")
PT = os.path.join(REG, "parameterTemplates", "schema.yaml")
PV = os.path.join(REG, "parameterValues", "schema.yaml")
# each TAPP -> its technique directory under techniqueProfile/
TECH_DIR = {
    "empaTAPP": "EMPA", "labxctTAPP": "XCT",
    "semTAPP": "SEM", "semImagingTAPP": "SEM-Imaging", "semFibsemTAPP": "SEM-FIBSEM",
    "semCompositionTAPP": "SEM-Composition", "solutionQicpmsTAPP": "Solution-Q-ICPMS",
    "solutionSficpmsTAPP": "Solution-SF-ICPMS", "temTAPP": "TEM",
    "solutionMcicpmsTAPP": "Solution-MC-ICPMS",
    # LA family, split by mass analyser to match the 2026-08-13 release, which replaced the single
    # combined LA-Q_SF workbook and the separate Horstwood geochronology one.
    "laQicpmsTAPP": "LA-Q-ICPMS", "laSficpmsTAPP": "LA-SF-ICPMS", "laMcicpmsTAPP": "LA-MC-ICPMS",
    "laQicpmsUPbTAPP": "LA-Q-ICPMS-UPb", "laSficpmsUPbTAPP": "LA-SF-ICPMS-UPb",
    "laMcicpmsUPbTAPP": "LA-MC-ICPMS-UPb",
}
CTX = {"schema": "http://schema.org/", "ada": "https://ada.astromat.org/metadata/"}

# Analyte-specific rows -> existing analyteColumns $def names (reused, not regenerated).
LAICPMS_ANALYTE_MAP = {
    "Spectrometer Dwell Time": ["spectrometerDwellTime"],
    "Detection Limit": ["detectionLimit"],
    "Detection Limit Method": ["detectionLimitMethod"],
    "Limit of Quantification (LOQ) Method": ["limitOfQuantification"],
    "Within-Session Analytical Precision and Assessment Method":
        ["withinSessionReproducibility", "withinSessionReproducibilityMethod"],
    "Between-Session (Long-Term) Analytical Precision and Assessment Method":
        ["betweenSessionReproducibility", "betweenSessionReproducibilityMethod"],
    "Analytical Accuracy and Assessment Method": ["analyticalAccuracy", "analyticalAccuracyMethod"],
    "Interfering Species": ["interferingSpecies"],
    "Interference Correction Method": ["IsobaricInterferenceCorrectionMethod"],
    "Isobaric Interference Corrections Applied": ["IsobaricInterferenceCorrection"],
}
# The 2026-08-13 release renamed every "Protocol …" identity row to "Procedure …" (a TAPP registers a
# procedure; a protocol is the published document). Matching is by item label, so the old names alone
# stopped recognising six identity rows in all sixteen release workbooks — they fell through to the
# parameter route and were emitted as schema:additionalProperty entries the schema does not enumerate
# (procedureReference and fundingSourceForProcedureDevelopment among the LA example errors). Both
# spellings are kept so the archived workbooks still route.
_IDENTITY_COMMON = {"Protocol Name", "Technique", "Protocol Author", "Laboratory",
                    "Protocol Start Date", "Funding Source for Protocol Development",
                    "Target Material", "Protocol Reference(s)", "Protocol DOI", "Laboratory ID",
                    "Procedure Name", "Procedure Author", "Procedure Start Date",
                    "Funding Source for Procedure Development", "Procedure Reference(s)",
                    "Procedure DOI"}

TAPP_CONFIGS = {
    "empaTAPP": {
        # Converted to the path-driven pipeline (2026-08-04) from the v-numbered workbook, replacing
        # the earlier matrix/`schema path` route (build_empa) + _tapp_lib publication examples.
        "xlsx": "tapp/Current TAPPs/EPMA_TAPP_v25.csv",
        "prefix": "empa",
        "component_types": ["ada:EMPAImage", "ada:EMPAImageMap", "ada:EMPAQEATabular",
                            "ada:EMPAImageCollection", "ada:EMPAESPCTabular", "ada:EMPAESPCPlot"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "EPMA/EMPA Technique-Aligned Protocol Profile (empaTAPP)",
        "description": ("Electron-probe microanalysis (EPMA/EMPA, WDS/EDS) extension of the base TAPP "
                        "definition, generated from tapp/Current TAPPs/EPMA_TAPP_v25.csv via the path-driven pipeline "
                        "(bootstrap_schemapaths.py + build_pathdriven.py)."),
        "detail_title": "EPMA/EMPA Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for EPMA/EMPA, reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    "labxctTAPP": {
        "xlsx": "tapp/Current TAPPs/Lab-XCT_TAPP_v21.csv",
        "prefix": "labxct",
        "component_types": ["ada:XCTVolume", "ada:XCTProjectionImageSet", "ada:XCTSegmentationVolume",
                            "ada:XCTRenderedImage", "ada:XCTQuantitativeTabular"],
        "base_items": _IDENTITY_COMMON | {"CT System Manufacturer and Model"},
        "analyte_map": {},
        "conditional_mode": "Multi-volume stitching",
        "enum_props": {"analyticalMode": ["Single-volume", "Multi-volume stitching",
                                          "Single-volume; Multi-volume stitching"]},
        "title": "Lab-XCT Technique-Aligned Protocol Profile (labxctTAPP)",
        "description": ("Laboratory X-ray computed tomography (polychromatic cone-beam) extension of "
                        "the base TAPP definition. Basic protocol-tier fields are required top-level "
                        "ada: properties; Advanced protocol-tier fields are schema:additionalProperty[] "
                        "PropertyValueSpecification entries. XCT has no per-element analyte axis, so no "
                        "ada:analyteTemplate is defined. Generated from tapp/Current TAPPs/Lab-XCT_TAPP_v21.csv by "
                        "tools/build_tapp.py."),
        "detail_title": "Lab-XCT Analysis Detail",
        "detail_description": ("Detail block for Lab-XCT hasPart items. Discriminates on "
                               "ada:componentType, carries analysis-level required properties and an "
                               "@id reference to a registered labxctTAPP definition, and per-dataset "
                               "schema:additionalProperty entries constrained via $refs to the "
                               "parameterValues registry plus a catch-all. Generated by tools/build_tapp.py."),
    },
    "temTAPP": {
        "xlsx": "tapp/Current TAPPs/TEM_TAPP_v21.csv",
        "prefix": "tem",
        # componentType placeholders — refine against the Components worksheet when available.
        "component_types": ["ada:TEMImage", "ada:STEMImage", "ada:TEMDiffractionPattern",
                            "ada:EELSSpectrum", "ada:TEMTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "TEM Technique-Aligned Protocol Profile (temTAPP)",
        "description": ("Transmission electron microscopy (TEM/STEM, incl. EDS/EELS) extension of the "
                        "base TAPP definition. Basic protocol-tier fields are required top-level ada: "
                        "properties; Advanced protocol-tier fields are schema:additionalProperty[] "
                        "entries; an ada:analyteTemplate carries per-element columns. Generated from "
                        "tapp/Current TAPPs/TEM_TAPP_v21.csv by tools/build_tapp.py."),
        "detail_title": "TEM Analysis Detail",
        "detail_description": ("Detail block for TEM hasPart items. Discriminates on ada:componentType, "
                               "carries analysis-level required properties and an @id reference to a "
                               "registered temTAPP definition, and per-dataset schema:additionalProperty "
                               "entries constrained via $refs to the parameterValues registry plus a "
                               "catch-all. Generated by tools/build_tapp.py."),
    },
    "semImagingTAPP": {
        "xlsx": "tapp/Current TAPPs/SEM_Imaging_TAPP_v14.csv",
        "prefix": "semImaging",
        "component_types": ["ada:SEMImage", "ada:BSEImage", "ada:CLImage", "ada:CLSpectrum",
                            "ada:EBSDMap", "ada:SEMTabular"],
        "base_items": _IDENTITY_COMMON,
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "SEM Imaging Technique-Aligned Protocol Profile (semImagingTAPP)",
        "description": ("Scanning electron microscopy imaging (SE/BSE/CL/EBSD) extension of the base "
                        "TAPP definition. Basic protocol-tier fields are required top-level ada: "
                        "properties; Advanced protocol-tier fields are schema:additionalProperty[] "
                        "entries. No ada:analyteTemplate (imaging has no per-element analyte axis). "
                        "Generated from tapp/Current TAPPs/SEM_Imaging_TAPP_v14.csv by tools/build_tapp.py."),
        "detail_title": "SEM Imaging Analysis Detail",
        "detail_description": ("Detail block for SEM imaging hasPart items. Discriminates on "
                               "ada:componentType, carries analysis-level required properties and an "
                               "@id reference to a registered semImagingTAPP definition, and per-dataset "
                               "schema:additionalProperty entries constrained via $refs to the "
                               "parameterValues registry plus a catch-all. Generated by tools/build_tapp.py."),
    },
    "semFibsemTAPP": {
        "xlsx": "tapp/Current TAPPs/SEM_FIBSEM_TAPP_v14.csv",
        "prefix": "semFibsem",
        "component_types": ["ada:FIBSEMVolume", "ada:FIBSEMImage", "ada:FIBSEMSegmentation",
                            "ada:FIBSEMTabular"],
        "base_items": _IDENTITY_COMMON,
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "FIB-SEM Technique-Aligned Protocol Profile (semFibsemTAPP)",
        "description": ("Focused-ion-beam SEM (FIB-SEM tomography, TEM lamella prep) extension of the "
                        "base TAPP definition. Basic protocol-tier fields are required top-level ada: "
                        "properties; Advanced protocol-tier fields are schema:additionalProperty[] "
                        "entries. No ada:analyteTemplate. Generated from tapp/Current TAPPs/SEM_FIBSEM_TAPP_v14.csv "
                        "by tools/build_tapp.py."),
        "detail_title": "FIB-SEM Analysis Detail",
        "detail_description": ("Detail block for FIB-SEM hasPart items. Discriminates on "
                               "ada:componentType, carries analysis-level required properties and an "
                               "@id reference to a registered semFibsemTAPP definition, and per-dataset "
                               "schema:additionalProperty entries constrained via $refs to the "
                               "parameterValues registry plus a catch-all. Generated by tools/build_tapp.py."),
    },
    # ---- new path-driven TAPPs (generated via bootstrap_schemapaths.py + build_pathdriven.py). The
    # matrix-specific CFG fields (component_types/base_items/analyte_map/conditional_mode/enum_props)
    # only feed build_tapp.build()'s registries/vocab/bblock pass; build_pathdriven then overwrites
    # the schemas from the schema paths. componentType consts are PROPOSED (refine vs Components ws).
    "semCompositionTAPP": {
        "xlsx": "tapp/Current TAPPs/SEM_Composition_TAPP_v22.csv",
        "prefix": "semComposition",
        "component_types": ["ada:SEMEDSSpectrum", "ada:SEMEDSMap", "ada:SEMWDSSpectrum",
                            "ada:SEMCompositionTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "SEM Composition (EDS/WDS) Technique-Aligned Protocol Profile (semCompositionTAPP)",
        "description": ("Scanning electron microscopy compositional microanalysis (EDS/WDS) extension of "
                        "the base TAPP definition, generated from tapp/Current TAPPs/SEM_Composition_TAPP_v22.csv via "
                        "the path-driven pipeline (bootstrap_schemapaths.py + build_pathdriven.py)."),
        "detail_title": "SEM Composition Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for SEM composition (EDS/WDS), "
                               "reusing CDIF/schema.org slots on the schema:Dataset root."),
    },
    "semTAPP": {
        "xlsx": "tapp/Current TAPPs/SEM_TAPP_v22.csv",
        "prefix": "sem",
        "component_types": ["ada:SEMImage", "ada:BSEImage", "ada:SEMEDSSpectrum", "ada:SEMEDSMap",
                            "ada:EBSDMap", "ada:SEMTabular"],
        "base_items": _IDENTITY_COMMON,
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "SEM Technique-Aligned Protocol Profile (semTAPP)",
        "description": ("Scanning electron microscopy superset (imaging + EDS/WDS composition + EBSD + "
                        "FIB-SEM) extension of the base TAPP definition, generated from "
                        "tapp/Current TAPPs/SEM_TAPP_v22.csv via the path-driven pipeline."),
        "detail_title": "SEM Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for SEM (superset), reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    "solutionMcicpmsTAPP": {
        # New to the pipeline with the 2026-08-13 delivery. Seeded from solutionQicpmsTAPP, which
        # already places 76% of its fields — the two share the whole solution-introduction and
        # ICP-MS core and differ in the multi-collector detector array.
        "xlsx": "TAPPS20260813/Current TAPPs/Solution_MC-ICP-MS_TAPP_v16.xlsx",
        "prefix": "solutionMcicpms",
        "component_types": ["ada:SolutionICPMSTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "Solution MC-ICP-MS Technique-Aligned Procedure Profile (solutionMcicpmsTAPP)",
        "description": ("Solution multi-collector ICP-MS extension of the base TAPP definition, "
                        "generated from TAPPS20260813/Current TAPPs/Solution_MC-ICP-MS_TAPP_v16.xlsx "
                        "via the path-driven pipeline."),
        "detail_title": "Solution MC-ICP-MS Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for solution MC-ICP-MS, "
                               "reusing CDIF/schema.org slots on the schema:Dataset root."),
    },
    "solutionQicpmsTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/Solution_Q-ICP-MS_TAPP_v17.xlsx",
        "prefix": "solutionQicpms",
        "component_types": ["ada:SolutionICPMSTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "Solution Q-ICP-MS Technique-Aligned Protocol Profile (solutionQicpmsTAPP)",
        "description": ("Solution quadrupole ICP-MS extension of the base TAPP definition, generated "
                        "from TAPPS20260813/Current TAPPs/Solution_Q-ICP-MS_TAPP_v17.xlsx via the path-driven pipeline."),
        "detail_title": "Solution Q-ICP-MS Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for solution Q-ICP-MS, reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    "solutionSficpmsTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/Solution_SF-ICP-MS_TAPP_v18.xlsx",
        "prefix": "solutionSficpms",
        "component_types": ["ada:SolutionICPMSTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "Solution SF-ICP-MS Technique-Aligned Protocol Profile (solutionSficpmsTAPP)",
        "description": ("Solution sector-field (high-resolution) ICP-MS extension of the base TAPP "
                        "definition, generated from TAPPS20260813/Current TAPPs/Solution_SF-ICP-MS_TAPP_v18.xlsx via the "
                        "path-driven pipeline."),
        "detail_title": "Solution SF-ICP-MS Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for solution SF-ICP-MS, reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    # ---- LA family. The 2026-08-13 release splits laser ablation by mass analyser and folds
    # geochronology into per-analyser U-Pb variants, retiring the combined docs/LA-Q_SF-ICPMS_v3 and
    # docs/LA-ICPMS_Geochron_Horstwood_v6 workbooks that laicpmsTAPP and geochronTAPP were built from.
    # The six sidecars were seeded from those two so the hand modelling carried over; see
    # docs/archive/README.md.
    "laQicpmsTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/LA-Q-ICP-MS_TAPP_v15.xlsx",
        "prefix": "laQicpms",
        "component_types": ["ada:LAICPMSTabular", "ada:LAICPMSMap", "ada:LAICPMSImage",
                            "ada:LAICPMSTransect"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": LAICPMS_ANALYTE_MAP,
        "conditional_mode": "",
        "enum_props": {},
        "title": "LA-Q-ICP-MS Technique-Aligned Procedure Profile (laQicpmsTAPP)",
        "description": ("Laser-ablation quadrupole ICP-MS extension of the base TAPP definition, "
                        "generated from TAPPS20260813/Current TAPPs/LA-Q-ICP-MS_TAPP_v15.xlsx via the "
                        "path-driven pipeline (bootstrap_schemapaths.py + build_pathdriven.py)."),
        "detail_title": "LA-Q-ICP-MS Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for LA-Q-ICP-MS, reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    "laSficpmsTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/LA-SF-ICP-MS_TAPP_v16.xlsx",
        "prefix": "laSficpms",
        "component_types": ["ada:LAICPMSTabular", "ada:LAICPMSMap", "ada:LAICPMSImage",
                            "ada:LAICPMSTransect"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": LAICPMS_ANALYTE_MAP,
        "conditional_mode": "",
        "enum_props": {},
        "title": "LA-SF-ICP-MS Technique-Aligned Procedure Profile (laSficpmsTAPP)",
        "description": ("Laser-ablation sector-field (high-resolution) ICP-MS extension of the base "
                        "TAPP definition, generated from TAPPS20260813/Current TAPPs/"
                        "LA-SF-ICP-MS_TAPP_v16.csv via the path-driven pipeline."),
        "detail_title": "LA-SF-ICP-MS Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for LA-SF-ICP-MS, reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    "laMcicpmsTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/LA-MC-ICPMS_TAPP_v13.xlsx",
        "prefix": "laMcicpms",
        "component_types": ["ada:LAICPMSTabular", "ada:LAICPMSMap", "ada:LAICPMSImage",
                            "ada:LAICPMSTransect"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": LAICPMS_ANALYTE_MAP,
        "conditional_mode": "",
        "enum_props": {},
        "title": "LA-MC-ICP-MS Technique-Aligned Procedure Profile (laMcicpmsTAPP)",
        "description": ("Laser-ablation multi-collector ICP-MS extension of the base TAPP definition, "
                        "generated from TAPPS20260813/Current TAPPs/LA-MC-ICPMS_TAPP_v13.xlsx via the "
                        "path-driven pipeline."),
        "detail_title": "LA-MC-ICP-MS Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for LA-MC-ICP-MS, reusing "
                               "CDIF/schema.org slots on the schema:Dataset root."),
    },
    "laQicpmsUPbTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/LA-Q-ICP-MS_UPb_TAPP_v16.xlsx",
        "prefix": "laQicpmsUPb",
        "component_types": ["ada:LAICPMSGeochronTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "LA-Q-ICP-MS U-Pb Geochronology TAPP (laQicpmsUPbTAPP)",
        "description": ("Laser-ablation quadrupole ICP-MS U-Pb geochronology extension of the base "
                        "TAPP definition, generated from TAPPS20260813/Current TAPPs/"
                        "LA-Q-ICP-MS_UPb_TAPP_v16.csv via the path-driven pipeline."),
        "detail_title": "LA-Q-ICP-MS U-Pb Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for LA-Q-ICP-MS U-Pb "
                               "geochronology, reusing CDIF/schema.org slots on the schema:Dataset root."),
    },
    "laSficpmsUPbTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/LA-SF-ICP-MS_UPb_TAPP_v17.xlsx",
        "prefix": "laSficpmsUPb",
        "component_types": ["ada:LAICPMSGeochronTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "LA-SF-ICP-MS U-Pb Geochronology TAPP (laSficpmsUPbTAPP)",
        "description": ("Laser-ablation sector-field ICP-MS U-Pb geochronology extension of the base "
                        "TAPP definition, generated from TAPPS20260813/Current TAPPs/"
                        "LA-SF-ICP-MS_UPb_TAPP_v17.csv via the path-driven pipeline."),
        "detail_title": "LA-SF-ICP-MS U-Pb Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for LA-SF-ICP-MS U-Pb "
                               "geochronology, reusing CDIF/schema.org slots on the schema:Dataset root."),
    },
    "laMcicpmsUPbTAPP": {
        "xlsx": "TAPPS20260813/Current TAPPs/LA-MC-ICPMS_UPb_TAPP_v13.xlsx",
        "prefix": "laMcicpmsUPb",
        "component_types": ["ada:LAICPMSGeochronTabular"],
        "base_items": _IDENTITY_COMMON | {"Analyte"},
        "analyte_map": {},
        "conditional_mode": "",
        "enum_props": {},
        "title": "LA-MC-ICP-MS U-Pb Geochronology TAPP (laMcicpmsUPbTAPP)",
        "description": ("Laser-ablation multi-collector ICP-MS U-Pb geochronology extension of the "
                        "base TAPP definition, generated from TAPPS20260813/Current TAPPs/"
                        "LA-MC-ICPMS_UPb_TAPP_v13.csv via the path-driven pipeline."),
        "detail_title": "LA-MC-ICP-MS U-Pb Analysis Detail",
        "detail_description": ("Dataset-level analysis-instance detail for LA-MC-ICP-MS U-Pb "
                               "geochronology, reusing CDIF/schema.org slots on the schema:Dataset root."),
    },
}

CFG = {}
TAPP = PARAM_BASE = VOCAB_BASE = TAPP_DIR = DETAIL_DIR = XLSX = None


def configure(tapp_name):
    global CFG, TAPP, PARAM_BASE, VOCAB_BASE, TAPP_DIR, DETAIL_DIR, XLSX
    if tapp_name not in TAPP_CONFIGS:
        raise SystemExit(f"Unknown TAPP {tapp_name!r}. Known: {sorted(TAPP_CONFIGS)}")
    CFG = TAPP_CONFIGS[tapp_name]
    TAPP = tapp_name
    PARAM_BASE = "ada:parameter/" + TAPP
    VOCAB_BASE = "ada:vocab/" + TAPP
    tech = TECH_DIR[TAPP]
    TAPP_DIR = os.path.join(TPROF, tech, "tapp")
    DETAIL_DIR = os.path.join(TPROF, tech, "detail")
    XLSX = os.path.join(ROOT, *CFG["xlsx"].split("/"))


# ---------- small helpers ----------
def norm(v):
    return " ".join(str(v).split()) if v is not None else ""


def camel(s):
    """camelCase a workbook item name into a CURIE local name.

    A CURIE local name must start with a letter ([A-Za-z][A-Za-z0-9]*), so an item whose name
    leads with a number — "3D Image Registration" — cannot simply be lower-camelled: the naive
    `3dImageRegistration` is rejected by the schema-path parser. Leading numeric tokens are moved
    to the end instead, giving `imageRegistration3D`, which is the convention already hand-authored
    in the sidecars for exactly these rows.
    """
    s = re.sub(r"\(.*?\)", "", s)
    s = re.sub(r"[^A-Za-z0-9 ]", " ", s).strip()
    parts = s.split()
    if not parts:
        return "x"
    trailing = []
    while len(parts) > 1 and parts[0][0].isdigit():
        trailing.append(parts.pop(0).upper())
    out = parts[0].lower() + "".join(p.capitalize() for p in parts[1:]) + "".join(trailing)
    return out if out[0].isalpha() else "n" + out   # all-numeric name: keep it legal


def field_name(item, sp, parsed):
    """Workbook-authoritative property/parameter base name (Default suffix stripped):
    the clean ada:<name> segment of the `schema path`, else the impl property:/parameter:
    tag name, else camelCase(item). Mirrors the analyteColumn naming so the workbook
    drives names; the camelCase(item) fallback covers rows without schema-path/impl names."""
    if "ada:" in sp and "methodParameters" not in sp and "analyteTemplate" not in sp:
        m = re.search(r"ada:([A-Za-z][A-Za-z0-9]*)", sp)
        if m:
            return re.sub(r"Default$", "", m.group(1))
    for tr in (parsed.get("tag_records") or []):
        if tr["kind"] in ("property", "parameter"):
            return re.sub(r"Default$", "", tr["name"])
    return camel(item)


def jtype(dt):
    d = dt.lower()
    if "integer" in d:
        return "integer"
    if "numeric" in d or "number" in d:
        return "number"
    if "boolean" in d:
        return "boolean"
    if d.startswith("date"):
        return "date"
    if "uri" in d or "doi" in d:
        return "uri"
    return "string"


def unit(dt):
    m = re.search(r"\(([^)]+)\)", dt)
    return m.group(1) if m else None


def meaningful(v):
    v = re.sub(r"\s*\[P[^\]]*\]", "", norm(v)).strip()
    if v in ("", "N", "N/A"):
        return False
    m = re.match(r"^(N/A|N)\b\s*", v)
    if m:
        rest = v[m.end():]
        if rest.startswith("("):
            depth = 0
            for i, ch in enumerate(rest):
                depth += (ch == "(") - (ch == ")")
                if ch == ")" and depth == 0:
                    rest = rest[i + 1:]
                    break
        if re.fullmatch(r"[/;,\-\s]*", rest.strip()):
            return False
    return True


def dump_yaml(obj):
    return yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, default_flow_style=False, width=100)


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def write_bblock_if_missing(bb_dir, name, abstract, tags, register="cdif-building-block-register"):
    """Scaffold a registered-BB bblock.json once (left untouched if present, so re-runs
    don't churn it)."""
    p = os.path.join(bb_dir, "bblock.json")
    if os.path.exists(p):
        return
    bb = {
        "$schema": "metaschema.yaml", "name": name, "abstract": abstract,
        "status": "under-development", "dateTimeAddition": "2026-06-07T00:00:00Z",
        "itemClass": "schema", "register": register, "version": "0.1",
        "dateOfLastChange": "2026-06-07",
        "link": "https://github.com/amds-ldeo/geochemBuildingBlocks",
        "maturity": "draft", "scope": "unstable", "tags": tags,
        "sources": [{"title": os.path.basename(CFG["xlsx"]) + " (TAPP worksheet)",
                     "link": "https://github.com/amds-ldeo/geochemBuildingBlocks/tree/main/docs"}],
    }
    write(p, json.dumps(bb, indent=2, ensure_ascii=False) + "\n")


def def_key(bare, existing=None):
    """Registry $def key for one generated def: always namespaced by TAPP prefix.

    The registries are shared across TAPPs and key $defs by name, but a def always embeds its own
    per-TAPP @id const — so two TAPPs can never produce an identical def for the same bare name.
    Across the ten path-driven TAPPs 102 names are shared and every one of them conflicts
    (detectionLimit is generated by seven). Namespacing unconditionally makes the key as
    unambiguous as the @id it carries, so all of them can coexist in one registry file.

    `existing` is accepted for call-site compatibility and no longer consulted: it used to hold
    only the names seen in the CURRENT build, so it caught same-TAPP collisions but never
    cross-TAPP ones — which are the ones that actually clash in the shared file.
    """
    return CFG["prefix"] + "_" + bare


def is_dual(b):
    return b["A"] in ("Basic", "Editable", "Advanced")


def methoddef_name(b):
    return b["name"] + ("Default" if is_dual(b) else "")


def param_template_def(b, existing):
    mdname = methoddef_name(b)
    name = def_key(mdname, existing)
    props = {
        "@id": {"const": PARAM_BASE + "/" + mdname},
        "@type": {"const": ["schema:PropertyValueSpecification"]},
        "schema:valueName": {"const": mdname},
        "schema:name": {"const": b["item"]},
        "ada:dataType": {"const": b["jtype"]},
        "ada:fieldScope": {"const": "session"},
        "schema:readonlyValue": {"const": not is_dual(b)},
        "ada:tier": {"const": "R"},
    }
    if b.get("unit") and b["unit"] != "free":
        props["schema:unitText"] = {"const": b["unit"]}
    return name, {name: {"title": b["item"], "description": b["desc"], "type": "object",
                         "properties": props,
                         "required": ["@id", "@type", "schema:valueName", "schema:name",
                                      "ada:dataType", "ada:fieldScope"]}}


def param_value_def(b, existing):
    bare = b["name"]
    name = def_key(bare, existing)
    has_unit = bool(b.get("unit") and b["unit"] != "free")
    props = {
        "@id": {"const": PARAM_BASE + "/" + bare},
        "@type": {"const": ["schema:PropertyValue"]},
        # schema:propertyID is a URI-shape identifier -> JSON-LD @id reference (CDIF convention),
        # and it is 0..*, so an array like every other repeatable property. The bare object form
        # validated here but not against the CDIF PropertyValue, which types propertyID as array.
        "schema:propertyID": {"const": [{"@id": PARAM_BASE + "/" + bare}]},
        "schema:name": {"const": b["item"]},
    }
    props["schema:value"] = ({"anyOf": [{"type": "number"}, {"type": "string"}]}
                             if b["jtype"] in ("number", "integer") else {"type": "string"})
    req = ["@id", "@type", "schema:propertyID", "schema:name", "schema:value"]
    if has_unit:
        props["schema:unitText"] = {"type": "string"}
        req.append("schema:unitText")
    return name, {name: {"title": b["item"], "description": b["desc"], "type": "object",
                         "properties": props, "required": req}}


def remove_owned_blocks(path, owner_substr):
    """Drop $def blocks whose body references owner_substr (this TAPP's @id), preserving
    formatting of other entries. Idempotent regen (remove before re-append)."""
    lines = open(path, encoding="utf-8").read().splitlines(keepends=True)
    out, i, removed = [], 0, []
    defs_re = re.compile(r"^  (\S.*):\s*$")
    while i < len(lines):
        m = defs_re.match(lines[i])
        if m:
            j = i + 1
            block = [lines[i]]
            while j < len(lines) and not defs_re.match(lines[j]):
                block.append(lines[j]); j += 1
            (removed.append(m.group(1)) if owner_substr in "".join(block) else out.extend(block))
            i = j
        else:
            out.append(lines[i]); i += 1
    open(path, "w", encoding="utf-8", newline="\n").write("".join(out))
    return removed


def append_defs(catalog_path, defs):
    frag = ""
    for name, body in defs.items():
        block = dump_yaml({name: body})
        frag += "\n" + "\n".join(("  " + ln) if ln else ln for ln in block.splitlines())
    with open(catalog_path, "a", encoding="utf-8", newline="\n") as f:
        f.write(frag.rstrip("\n") + "\n")
    print("appended", len(defs), "$defs to", os.path.relpath(catalog_path, ROOT))


def existing_keys(path):
    d = yaml.safe_load(open(path, encoding="utf-8")) or {}
    return set((d.get("$defs") or {}).keys())


def write_vocab(b):
    import _tapp_lib as _L
    _L.TAPP_NAME = TAPP  # scheme @id is ada:vocab/<TAPP>/<name>
    obj = _L.vocab_obj(b["name"], b["item"], b["desc"][:300], b["terms"])
    write(os.path.join(VOCAB_DIR, CFG["prefix"] + "_" + b["name"] + ".json"),
          json.dumps(obj, indent=2, ensure_ascii=False) + "\n")


# ---------- routing ----------
# ---------- Step 3: minimal-annotation inputs (content + central roles + sidecar) ----------
# route() derives every row's decision from the plain content columns plus two annotation
# sources that live OUTSIDE the workbook: tools/tapp_role_items.json (Layer B: recurring
# inherited/description/analyte-identifier rows, by Metadata Item name) and a per-workbook
# sidecar docs/<workbook>.overrides.json (the residual: curated names, analyte-column
# specs, technique-specific role skips). This lets a raw Drive workbook — with no
# schema-path / implementation-notes columns — generate directly. The equivalence harness
# (tools/verify_tapp_overrides.py) proves this reproduces the old annotation-driven route().
CENTRAL_ROLES_FILE = os.path.join(ROOT, "tools", "tapp_role_items.json")


def _norm_item(s):
    return " ".join(str(s).split()).lower() if s is not None else ""


def load_central_roles():
    if os.path.exists(CENTRAL_ROLES_FILE):
        with open(CENTRAL_ROLES_FILE, encoding="utf-8") as f:
            return json.load(f)
    return {}


def load_sidecar():
    # docs/<wb>.overrides.json — ours, so it lives with the sidecars, not in Ruolin's delivery
    p = os.path.join(ROOT, "docs", os.path.splitext(os.path.basename(XLSX))[0] + ".overrides.json")
    if os.path.exists(p):
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return {}


def route():
    import _tapp_lib as _L
    from collections import OrderedDict
    rows = tapp_source.rows(XLSX)          # .csv or .xlsx — the library moved to CSV
    hdr = rows[0]
    H = [norm(v).lower() for v in hdr]
    lit = next((i for i, v in enumerate(H) if v == "literature assessment"), None)
    comment_col = next((i for i, v in enumerate(H) if v.startswith("comment")), None)
    boundary = lit if lit is not None else len(hdr)
    cov_start = (lit + 1) if lit is not None else len(hdr)
    # Mode columns: the Y/N boolean columns between 'comment' and 'Literature Assessment'
    # (their headers are the ada:analyticalMode enum options). Any leftover guidance columns
    # in that span are text, so the all-cells-in-{Y,N} filter excludes them; this works on a
    # raw Drive workbook (no guidance columns) identically.
    mode_cols = []
    if comment_col is not None:
        for i in range(comment_col + 1, boundary):
            vals = [norm(rr[i]).upper() for rr in rows[1:] if i < len(rr) and norm(rr[i])]
            if vals and all(v in ("Y", "N") for v in vals):
                mode_cols.append(i)
    mode_names = [norm(hdr[i]) for i in mode_cols]
    R = {"tapp_prop": [], "method_param": [], "method_value": [], "detail_req": [], "detail_addl": [],
         "analyte_cols": [], "analyte_defs": OrderedDict(), "vocab": [], "mode_names": mode_names}
    central = load_central_roles()
    sidecar = load_sidecar()
    R["tapp_description"] = sidecar.get("_tappDescription")  # file-level boilerplate, not a workbook row
    _L.TAPP_NAME = TAPP  # for analyte_column_obj / registry @ids (no TAPP_PROFILES dependency)
    for r in rows[1:]:
        item = norm(r[0])
        if not item or re.match(r"^\d+\.\s", item):
            continue
        P, A, dt, ex = norm(r[2]), norm(r[3]), norm(r[4]), norm(r[5])
        modes = [norm(hdr[i]) for i in mode_cols if i < len(r) and norm(r[i]).upper() == "Y"]
        cov = sum(1 for i in range(cov_start, len(r)) if meaningful(r[i]))
        ov = sidecar.get(item, {})
        rec = {"item": item, "name": ov.get("name") or camel(item), "P": P, "A": A, "jtype": jtype(dt),
               "unit": unit(dt), "desc": norm(r[1]), "allowed": ex, "cov": cov,
               "multivol_only": (modes == [CFG["conditional_mode"]])}
        # analyte-template columns: from the sidecar's per-column {name, dtype, readOnly}.
        analyte_cols = ov.get("analyteColumn")
        if analyte_cols:
            cols = []
            for c in analyte_cols:
                cols.append(c["name"])
                R["analyte_defs"][c["name"]] = _L.analyte_column_obj(
                    c["name"], item, rec["desc"], c["dtype"], None, c["readOnly"])
            R["analyte_cols"].append({**rec, "cols": cols})
            continue
        # rows that are NOT new TAPP properties (skipped): identity/base fields (content, by
        # name), Layer-B central roles (inherited/description/analyte-identifier), and any
        # per-workbook role override in the sidecar.
        if item in CFG["base_items"] or _norm_item(item) in central or ov.get("role"):
            continue
        # analyticalMode is rendered as a list-of-strings with a mode-derived enum (rule 1),
        # not a vocab-referencing field, so it needs no DefinedTermSet.
        if rec["name"] != "analyticalMode" and ("controlled" in dt.lower() or dt.lower().startswith("boolean")):
            terms = (["Yes", "No"] if dt.lower().startswith("boolean")
                     else [p.strip().strip("'\"") for p in ex.split("|")
                           if p.strip() and not p.strip().lower().startswith("e.g")
                           and "specify" not in p.strip().lower()])
            if terms:
                R["vocab"].append({**rec, "terms": terms})
        if P == "Basic":
            R["tapp_prop"].append(rec)
        elif P == "Advanced":
            # Advanced + editable (dual) -> PropertyValueSpecification template;
            # Advanced + read-only -> PropertyValue (fixed protocol value).
            (R["method_param"] if is_dual(rec) else R["method_value"]).append(rec)
        if A == "Basic":
            R["detail_req"].append(rec)
        elif A in ("Editable", "Advanced"):
            R["detail_addl"].append(rec)
    return R


# ---------- build ----------
def build():
    os.makedirs(TAPP_DIR, exist_ok=True)
    os.makedirs(DETAIL_DIR, exist_ok=True)
    R = route()
    for b in R["vocab"]:
        write_vocab(b)

    remove_owned_blocks(PT, PARAM_BASE + "/")
    remove_owned_blocks(PV, PARAM_BASE + "/")
    pt_existing, pv_existing = existing_keys(PT), existing_keys(PV)

    pt_defs, pt_keys = {}, []
    for b in R["method_param"]:
        n, d = param_template_def(b, pt_existing); pt_defs.update(d); pt_keys.append(n); pt_existing.add(n)
    append_defs(PT, pt_defs)

    pv_defs, pv_keys, pv_ids, seen = {}, [], [], set()
    for b in R["detail_addl"]:
        if b["name"] in seen:
            continue
        seen.add(b["name"])
        n, d = param_value_def(b, pv_existing); pv_defs.update(d); pv_keys.append(n)
        pv_ids.append(PARAM_BASE + "/" + b["name"]); pv_existing.add(n)
    # Advanced + Read-Only -> PropertyValue (fixed protocol value) in parameterValues,
    # referenced from the TAPP schema:additionalProperty (alongside the editable specs).
    mv_keys = []
    for b in R["method_value"]:
        if b["name"] in seen:
            continue
        seen.add(b["name"])
        n, d = param_value_def(b, pv_existing); pv_defs.update(d); mv_keys.append(n); pv_existing.add(n)
    append_defs(PV, pv_defs)

    acols = []
    for b in R["analyte_cols"]:
        for c in b["cols"]:
            if c not in acols:
                acols.append(c)
    if R.get("analyte_defs"):
        import _tapp_lib as _L
        _L.TAPP_NAME = TAPP
        _L.write_analyte_columns_registry(R["analyte_defs"])

    # ---- TAPP schema ----
    tapp_props, basic_required = {}, []
    if R.get("tapp_description"):
        # Per-TAPP scope boilerplate as an editable JSON Schema default (the base tappDefinition
        # declares schema:description as a plain string; this layer only pre-fills it). Lab-specific
        # instances of the TAPP may amend or extend the text.
        tapp_props["schema:description"] = {
            "type": "string", "default": R["tapp_description"],
            "description": ("Human-readable statement of this protocol's scope, pre-filled as editable "
                            "boilerplate; lab-specific instances may amend or extend it.")}
    enum_props = CFG["enum_props"]
    mode_names = R.get("mode_names") or []
    for b in R["tapp_prop"]:
        key = "ada:" + b["name"] + ("Default" if b["A"] == "Editable" else "")
        if b["name"] == "analyticalMode":
            key = "ada:analyticalMode"  # never carries a …Default suffix
            # always a LIST of strings; options are the mode-column headers
            items = {"type": "string"}
            if mode_names:
                items["enum"] = list(mode_names)
            tapp_props[key] = {"description": b["desc"], "type": "array", "items": items}
        elif b["name"] in enum_props:
            tapp_props[key] = {"description": b["desc"], "type": "string",
                               "enum": with_sentinel(enum_props[b["name"]])}
        elif b["jtype"] in ("number", "integer"):
            tapp_props[key] = {"description": b["desc"], "anyOf": [{"type": "number"}, {"type": "string"}]}
        else:
            tapp_props[key] = {"description": b["desc"], "type": "string"}
        if b["cov"] > 0:
            basic_required.append(key)
    if acols:
        ac_refs = [{"$ref": "../../../../BaseSchema/tappDefinition/schema.yaml#/$defs/AnalyteIdentifierColumn"}] + \
                  [{"$ref": "../../../../registry/analyteColumns/schema.yaml#/$defs/" + c} for c in acols]
        ac_contains = [{"contains": {"$ref": "../../../../registry/analyteColumns/schema.yaml#/$defs/" + c},
                        "minContains": 0, "maxContains": 1} for c in acols]
        tapp_props["ada:analyteTemplate"] = {"type": "object", "properties": {
            "ada:analyteColumns": {"type": "array", "items": {"anyOf": ac_refs}, "allOf": ac_contains}}}
    sap_refs = [{"$ref": "../../../../registry/parameterTemplates/schema.yaml#/$defs/" + n} for n in pt_keys] + \
               [{"$ref": "../../../../registry/parameterValues/schema.yaml#/$defs/" + n} for n in mv_keys]
    sap_contains = [{"contains": {"$ref": "../../../../registry/parameterTemplates/schema.yaml#/$defs/" + n},
                     "minContains": 0, "maxContains": 1} for n in pt_keys] + \
                   [{"contains": {"$ref": "../../../../registry/parameterValues/schema.yaml#/$defs/" + n},
                     "minContains": 0, "maxContains": 1} for n in mv_keys]
    if sap_refs:  # omit the overlay constraint when the technique has no Advanced params
        tapp_props["schema:additionalProperty"] = {
            "type": "array",
            "description": ("Method-level Advanced-protocol parameters. Editable parameters are "
                            "schema:PropertyValueSpecification entries (…Default name; the per-dataset value "
                            "lives in the detail block); read-only parameters are schema:PropertyValue entries "
                            "carrying the fixed protocol value in schema:value."),
            "items": {"anyOf": sap_refs}, "allOf": sap_contains}
    tapp_schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": CFG["title"], "description": CFG["description"],
        "allOf": [{"$ref": "../../../../BaseSchema/tappDefinition/schema.yaml"},
                  {"type": "object", "properties": tapp_props, "required": basic_required}]}
    write(os.path.join(TAPP_DIR, "schema.yaml"), dump_yaml(tapp_schema))

    # ---- detail schema ----
    req = ["ada:componentType"]
    block1 = {
        "ada:componentType": {"anyOf": [{"const": c} for c in CFG["component_types"]]},
        "schema:measurementTechnique": {"type": "array", "items": {"type": "object",
            "description": f"@id reference to a registered {TAPP} TAPP definition.",
            "properties": {"@id": {"type": "string", "format": "uri"}}, "required": ["@id"]}}}
    for b in R["detail_req"]:
        key = "ada:" + b["name"]
        if b["jtype"] in ("number", "integer"):
            # accept a typed number OR a qualified string (publication fidelity, e.g. "~380 slices")
            block1[key] = {"description": b["desc"], "anyOf": [{"type": b["jtype"]}, {"type": "string"}]}
        elif b["jtype"] == "boolean":
            block1[key] = {"description": b["desc"], "type": "boolean"}
        else:
            block1[key] = {"description": b["desc"], "type": "string"}
        if not b["multivol_only"]:
            req.append(key)
    pv_branches = [{"$ref": "../../../../registry/parameterValues/schema.yaml#/$defs/" + n} for n in pv_keys]
    catchall = {"type": "object",
        "description": f"Catch-all for additional schema:PropertyValue entries beyond the {TAPP}-derived catalog.",
        "properties": {"@type": {"type": "array", "items": {"type": "string"},
                                 "contains": {"const": "schema:PropertyValue"}},
                       "schema:propertyID": {"type": "object", "required": ["@id"],
                                             "properties": {"@id": {"type": "string", "not": {"enum": pv_ids}}}}},
        "required": ["@type", "schema:propertyID"]}
    detail = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": CFG["detail_title"], "description": CFG["detail_description"],
        "allOf": [{"type": "object", "properties": block1, "required": req},
                  {"type": "object", "properties": {"schema:additionalProperty": {
                      "type": "array", "description": "Per-dataset schema:PropertyValue entries. All optional.",
                      "items": {"anyOf": pv_branches + [catchall]}}}}]}
    write(os.path.join(DETAIL_DIR, "schema.yaml"), dump_yaml(detail))

    base_tags = ["ada", "astromat", "tapp", CFG["prefix"].lower(), "technique-protocol"]
    write_bblock_if_missing(TAPP_DIR, CFG["title"], CFG["description"], base_tags)
    write_bblock_if_missing(DETAIL_DIR, CFG["detail_title"], CFG["detail_description"],
                            ["ada", "astromat", "instrument", CFG["prefix"].lower()])

    os.makedirs(os.path.join(ROOT, "docs", "new_tapps202606"), exist_ok=True)
    json.dump({"tapp_props": list(tapp_props.keys()), "pt_keys": pt_keys, "pv_keys": pv_keys,
               "analyte_cols": acols, "detail_req": [b["name"] for b in R["detail_req"]],
               "detail_req_multivol": [b["name"] for b in R["detail_req"] if b["multivol_only"]],
               "component_types": CFG["component_types"], "basic_required": basic_required,
               "basic_props": [{"key": "ada:" + b["name"] + ("Default" if b["A"] == "Editable" else ""),
                                "item": b["item"], "jtype": b["jtype"], "cov": b["cov"],
                                "required": b["cov"] > 0} for b in R["tapp_prop"]]},
              open(os.path.join(ROOT, "docs", "new_tapps202606", CFG["prefix"] + "_gen_index.json"), "w"), indent=1)
    print(f"DONE {TAPP}: tapp_prop={len(R['tapp_prop'])} method_param={len(pt_keys)} "
          f"detail_req={len(R['detail_req'])} detail_addl={len(pv_keys)} analyteCols={len(acols)} vocab={len(R['vocab'])}")


# ---------- empaTAPP: schema-path + matrix routing over the _tapp_lib reader/emitters ----------
# empaTAPP is the evolved-past prototype workbook. Rather than bend the generic
# generator to its quirks, it is routed by the SAME canonical matrix as the other
# TAPPs (Protocol/Analysis tier columns) with the `schema path` column resolving
# the special roles (analyteColumn / analyte-identifier / schema:description /
# inherited base field / instrument). The rich emitters + registry writers +
# rich per-pub example builder live in _tapp_lib and are reused as a library;
# only the routing brain is build_tapp's (matrix), retiring _tapp_lib's old
# impl-tag-kind routing for empa.

_TIER_NORM = {"basic": "Basic", "editable": "Editable", "advanced": "Advanced",
              "read-only": "Read-Only", "readonly": "Read-Only", "read only": "Read-Only",
              "n/a": "N/A", "na": "N/A", "": ""}


def _norm_tier(v):
    return _TIER_NORM.get((v or "").strip().lower(), (v or "").strip())


def _empa_role(sp):
    """Resolve a row's structural role from its `schema path` value."""
    s = sp or ""
    if "ada:analyteTemplate.ada:analyteColumns" in s:
        return "analyteColumn"
    if "ada:analyteTemplate.ada:defaultAnalytes" in s:
        return "analyteIdentifier"
    # Advanced method parameter: new `schema:additionalProperty[...]` convention or the
    # legacy `ada:methodParameters[]`. Checked before the description/inherited branches
    # so additionalProperty paths (which sit under $MethodDefinition with no ada:) are not
    # mistaken for inherited base fields.
    if "schema:additionalProperty" in s or "methodParameters" in s:
        return "field"
    if "schema:description" in s:
        return "description"
    if s.startswith("$MethodDefinition") and "ada:" not in s:
        return "inherited"            # identity / instrument / inherited base field
    return "field"                    # regular property-or-parameter (matrix decides home)


_CLEAN_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")


def _empa_base_name(row):
    """Base property/parameter name: clean ada:<name> segment of the schema path
    (Default suffix stripped), else the impl-notes tag name, else camelCase(item)."""
    sp = row.get("schema_path") or ""
    if "ada:" in sp and "methodParameters" not in sp and "analyteTemplate" not in sp:
        seg = sp.split("ada:")[-1].strip()
        if _CLEAN_NAME.match(seg):
            return re.sub(r"Default$", "", seg)
    tags = (row.get("parsed") or {}).get("tags") or []
    if tags:
        return tags[0][1]
    return camel(row["item"])


# A controlled field records what a lab did. When a source -- typically a publication being
# transcribed -- does not state it, "missing" says so explicitly, which omission cannot: an absent
# key is indistinguishable from "not applicable" or "nobody looked". It is admitted by every
# generated enum for that reason, and deliberately NOT published as a concept in the vocabulary
# (vocab_obj drops it alongside N/A and None) -- it is the absence of a value, not one of them.
SENTINEL = "missing"


def with_sentinel(values):
    """The enum as constrained in the schema: the controlled values plus the sentinel."""
    out = list(values)
    if SENTINEL not in out:
        out.append(SENTINEL)
    return out


def route_empa(rows, L):
    """Matrix + schema-path routing for empaTAPP, producing the classification
    structures consumed by _tapp_lib's build_schema_yaml / registry writers."""
    # --- vocab dedup by sorted enum tuple (mirrors _tapp_lib._classify_rows) ---
    enum_to_vocab = {}
    for row in rows:
        enum = (row.get("parsed") or {}).get("enum")
        if not enum:
            continue
        key = tuple(sorted(enum))
        if key in enum_to_vocab:
            continue
        # Vocab name mirrors _tapp_lib._classify_rows: first impl tag name, else the
        # slugified item (case preserved — do NOT camelCase, so e.g. "Technique"
        # stays "Technique", matching the existing shared vocab file).
        tags = (row.get("parsed") or {}).get("tags") or []
        name = tags[0][1] if tags else re.sub(r"[^A-Za-z0-9]+", "_", row["item"]).strip("_")
        enum_to_vocab[key] = name
        L.share_or_write_catalog(L.VOCAB_DIR / f"{name}.json",
                                 L.vocab_obj(name, row["item"] or name, row.get("desc") or "", enum))

    def vocab_for(enum):
        return enum_to_vocab.get(tuple(sorted(enum))) if enum else None

    schema_properties, required_props = [], []
    by_item = {}  # item -> placement record for the example builder
    analyte_column_names, parameter_names, method_value_names, detail_param_names = [], [], [], []
    analyte_column_defs = __import__("collections").OrderedDict()
    parameter_template_defs = __import__("collections").OrderedDict()
    param_value_defs = __import__("collections").OrderedDict()
    seen_pv = set()

    for row in rows:
        item = row.get("item")
        if not item or re.match(r"^\d+\.\s", item):
            continue
        role = _empa_role(row.get("schema_path"))
        if role in ("inherited", "analyteIdentifier", "description"):
            continue  # handled by the base TAPP / instrument constraint / example builder
        P = _norm_tier(row.get("P"))
        A = _norm_tier(row.get("A"))
        parsed = row.get("parsed") or {}
        enum = parsed.get("enum")
        dtype = parsed.get("dtype") or row.get("dtype_col")
        jt = L.map_dtype(dtype)
        vname = vocab_for(enum)
        name = _empa_base_name(row)
        ro = parsed.get("readOnly")

        if role == "analyteColumn":
            analyte_column_names.append(name)
            analyte_column_defs[name] = L.analyte_column_obj(
                name, item, row.get("desc") or "", dtype, vname,
                ro if ro is not None else (A == "Read-Only"))
            continue

        # regular field — matrix decides the home(s)
        dual = A in ("Basic", "Editable", "Advanced")
        rec = {"role": "field", "P": P, "A": A, "name": name, "dual": dual,
               "enum": list(enum) if enum else None, "dtype": dtype,
               "detail": A in ("Editable", "Advanced")}
        if P == "Basic":
            key = "ada:" + name + ("Default" if A == "Editable" else "")
            rec["tapp_key"] = key
            if enum:
                block = {"description": row.get("desc") or "", "type": "string", "enum": with_sentinel(enum)}
            elif jt in ("number", "integer"):
                block = {"description": row.get("desc") or "",
                         "anyOf": [{"type": "number"}, {"type": "string"}]}
            elif jt == "boolean":
                block = {"description": row.get("desc") or "", "type": "boolean"}
            else:
                block = {"description": row.get("desc") or "", "type": "string"}
            schema_properties.append((key, block))
            cov = sum(1 for v in (row.get("pubs") or []) if L._pub_meaningful(v))
            if cov > 0:
                required_props.append(key)
        elif P == "Advanced":
            if dual:
                # editable -> PropertyValueSpecification (…Default name)
                mdname = name + "Default"
                rec["mdname"] = mdname
                rec["ro_value"] = False
                parameter_names.append(mdname)
                parameter_template_defs[mdname] = L.parameter_obj(
                    mdname, item, row.get("desc") or "", dtype, vname, False)
            else:
                # read-only -> PropertyValue (fixed protocol value) in parameterValues
                rec["mdname"] = name
                rec["ro_value"] = True
                if name not in param_value_defs:
                    method_value_names.append(name)
                    param_value_defs[name] = L.additional_property_obj(
                        name, item, row.get("desc") or "", row.get("dtype_col"), vname, dtype)
        by_item[item] = rec

        # detail side (per-dataset value) — Analysis Editable/Advanced
        if A in ("Editable", "Advanced") and name not in seen_pv:
            seen_pv.add(name)
            detail_param_names.append(name)
            param_value_defs[name] = L.additional_property_obj(
                name, item, row.get("desc") or "", row.get("dtype_col"), vname, dtype)

    # dedupe schema_properties (last wins)
    seen = {}
    for k, b in schema_properties:
        seen[k] = b
    schema_properties = list(seen.items())
    required_props = [k for k in dict.fromkeys(required_props) if k in seen]

    return {
        "schema_properties": schema_properties, "required_props": required_props,
        "analyte_column_names": analyte_column_names, "analyte_column_defs": analyte_column_defs,
        "parameter_names": parameter_names, "parameter_template_defs": parameter_template_defs,
        "method_value_names": method_value_names,
        "detail_param_names": detail_param_names, "param_value_defs": param_value_defs,
        "by_item": by_item,
    }


def _regen_detail_addl_constraint(L, detail_param_names):
    """Rewrite ONLY detailEMPA/schema.yaml allOf[1] (the schema:additionalProperty
    constraint) to reference the current parameterValues $defs + catch-all,
    preserving the hand-authored allOf[0]."""
    from ruamel.yaml import YAML
    sp = L.DETAIL_EMPA / "schema.yaml"
    if not sp.exists():
        return
    y = YAML()
    y.preserve_quotes = True
    y.width = 4096
    y.indent(mapping=2, sequence=4, offset=2)
    doc = y.load(open(sp, encoding="utf-8"))
    names = sorted(detail_param_names)
    pvbase = "../../../../registry/parameterValues/schema.yaml#/$defs/"
    anyof = [{"$ref": pvbase + n} for n in names]
    anyof.append({
        "type": "object",
        "description": ("Catch-all for additional schema:PropertyValue entries beyond those "
                        "enumerated in the empaTAPP-derived catalog above."),
        "properties": {
            "@type": {"type": "array", "items": {"type": "string"},
                      "contains": {"const": "schema:PropertyValue"}},
            "schema:propertyID": {"type": "object", "required": ["@id"], "properties": {
                "@id": {"type": "string",
                        "not": {"enum": [f"ada:parameter/empaTAPP/{n}" for n in names]}}}},
        },
        "required": ["@type", "schema:propertyID"],
    })
    block1 = {"type": "object", "properties": {"schema:additionalProperty": {
        "type": "array",
        "description": ("Per-dataset schema:PropertyValue entries for this EMPA dataset. Each item "
                        "is any of the empaTAPP-derived parameter types or (via the catch-all "
                        "branch) any other PropertyValue. All entries are optional — include only "
                        "the parameters you have values for."),
        "items": {"anyOf": anyof}}}}
    doc["allOf"][1] = L._to_commented(block1)
    with open(sp, "w", encoding="utf-8") as f:
        y.dump(doc, f)
    print(f"  rewrote detailEMPA allOf[1] additionalProperty constraint ({len(names)} PV refs)")


def build_empa():
    """Generate empaTAPP via the canonical matrix router + _tapp_lib emitters.
    Reuses _tapp_lib for the rich emitters, registry writers, instrument hasPart
    constraint, and (hand-authored) detail schema preservation."""
    import _tapp_lib as L
    L.CATALOG_CONFLICTS.clear()
    L.configure("empaTAPP", os.path.relpath(XLSX, ROOT))
    rows = L.read_rows()
    print(f"empaTAPP: read {len(rows)} rows from {os.path.relpath(XLSX, ROOT)}")
    cls = route_empa(rows, L)

    instrument = L.build_haspart_constraint(rows)
    L.build_schema_yaml(cls["schema_properties"], cls["analyte_column_names"],
                        cls["parameter_names"], instrument, required_props=cls["required_props"],
                        value_param_names=cls["method_value_names"])
    L.write_analyte_columns_registry(cls["analyte_column_defs"])
    L.write_parameter_templates_registry(cls["parameter_template_defs"])
    L.write_parameter_values_registry(cls["param_value_defs"])
    # detailEMPA/schema.yaml: allOf[0] is hand-authored (ada:spectrometersUsed,
    # ada:signalUsed, componentType enum, measurementTechnique) and preserved.
    # Only allOf[1] (the schema:additionalProperty constraint) is regenerated to
    # track the current detail PV set (one $ref per readOnly:false parameter + catch-all).
    _regen_detail_addl_constraint(L, cls["detail_param_names"])

    # ---- per-publication examples (matrix-routed via route_map) ----
    prop_type = {}
    for k, b in cls["schema_properties"]:
        prop_type[k] = ("number" if "anyOf" in b else b.get("type", "string"))
    req_set = set(cls["required_props"])
    rmap = cls["by_item"]
    examples_yaml = []
    n_tapp = n_detail = 0
    for i, (pcode, plabel) in enumerate(L._pubs()):
        empa_ex, detail_ex = L.example_for_pub(i, plabel, rows, route_map=rmap)
        for key, _b in cls["schema_properties"]:
            present = key in empa_ex
            ok = present and L._pub_meaningful(empa_ex[key])
            if key in req_set:
                if not ok:
                    empa_ex[key] = (-9999 if prop_type.get(key) == "number" else "missing")
            elif present and not ok:
                del empa_ex[key]
        L.write_json(L.BB / f"exampleempaTAPP-{pcode}.json", empa_ex)
        n_tapp += 1
        examples_yaml.append((pcode, plabel))
        if detail_ex.get("schema:additionalProperty"):
            L.write_json(L.DETAIL_EMPA / f"exampledetailEMPA-{pcode}.json", detail_ex)
            n_detail += 1
    L._write_examples_yaml(examples_yaml)
    print(f"  wrote {n_tapp} empaTAPP + {n_detail} detailEMPA examples")

    os.makedirs(os.path.join(ROOT, "docs", "new_tapps202606"), exist_ok=True)
    json.dump({"schema_properties": [k for k, _ in cls["schema_properties"]],
               "required_props": cls["required_props"],
               "analyte_column_names": sorted(cls["analyte_column_names"]),
               "parameter_names": sorted(cls["parameter_names"]),
               "detail_param_names": sorted(cls["detail_param_names"]),
               "basic_props": [{"key": k, "required": k in set(cls["required_props"])}
                               for k, _ in cls["schema_properties"]]},
              open(os.path.join(ROOT, "docs", "new_tapps202606", "empa_gen_index.json"), "w"), indent=1)
    print(f"DONE empaTAPP: props={len(cls['schema_properties'])} "
          f"(required {len(cls['required_props'])}) params={len(cls['parameter_names'])} "
          f"analyteCols={len(cls['analyte_column_names'])} detailValues={len(cls['detail_param_names'])}")
    if L.CATALOG_CONFLICTS:
        print(f"  {len(L.CATALOG_CONFLICTS)} catalog conflict(s) — see warnings above.")


def main():
    if len(sys.argv) < 2:
        raise SystemExit(f"usage: build_tapp.py <tapp_name>   known: {sorted(TAPP_CONFIGS)}")
    configure(sys.argv[1])
    if CFG.get("mode") == "empa":
        build_empa()
    else:
        build()


if __name__ == "__main__":
    main()
