"""Generate the detail<XXX> building block (per-dataset PropertyValue catalog +
parametersConstraint.yaml) from a TAPP_<technique>_filled.xlsx spreadsheet.

Usage:
    python tools/build_detail_BB.py [TAPP_NAME] [XLSX_PATH]

Defaults: empaTAPP / docs/TAPP_EPMA_filled.xlsx → writes
_sources/geochemProperties/detailEMPA/parametersConstraint.yaml plus
parameterValues catalog files at
_sources/techniqueProtocols/parameterValues/<name>.json.

The detail BB's own schema.yaml is hand-authored (componentType enum,
spectrometersUsed, signalUsed, schema:measurementTechnique anyOf-link to the
TAPP definition) and uses `allOf: [- {$ref: parametersConstraint.yaml}]` to
fold in the constraint generated by this tool.
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _tapp_lib  # noqa: E402


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("tapp_name", nargs="?", default="empaTAPP",
                        help="TAPP name (e.g. empaTAPP). Default: empaTAPP.")
    parser.add_argument("xlsx", nargs="?", default="docs/TAPP_EPMA_filled.xlsx",
                        help="Path to the filled TAPP spreadsheet. Default: docs/TAPP_EPMA_filled.xlsx.")
    parser.add_argument("--pub", action="append",
                        help="Only regen examples for these publication codes (e.g. --pub P0). "
                             "Repeat for multiple. Schema/catalog artifacts always rebuild.")
    args = parser.parse_args()
    _tapp_lib.configure(args.tapp_name, args.xlsx)
    _tapp_lib.build_detail_artifacts(pub_filter=args.pub)


if __name__ == "__main__":
    main()
