#!/usr/bin/env python3
"""Who owns each shared-registry def — the legacy route, the path-driven route, or both?

The registries under _sources/registry are written by TWO generators reading DIFFERENT sources:

  legacy       build_tapp.py / _tapp_lib.py, from the richer annotated workbooks
  path-driven  schema_path_emitter.build(), from the docs/*.schemapaths.csv sidecars

build_pathdriven currently publishes only the keyed-table registries (analyteColumns,
reportedPropertyColumns, channelColumns); parameterTemplates and parameterValues are legacy-owned.
Whether to publish those too is an open decision, and it cannot be answered without knowing how far
the two routes actually overlap and where they disagree. That is what this reports.

Identity is the def's `@id` const, not its $def key — the same parameter can sit under different
keys, and _write_registry upserts on @id.

Per registry, each def falls into one bucket:

  agree          the path-driven route generates this @id and its body is byte-identical
  DIFFER         generated, but the body differs -> publishing would OVERWRITE the stored one
  legacy-only    in the registry, not generated by any sidecar -> publishing leaves it untouched,
                 but it also never gets corrected by a generator fix
  would-ADD      the path-driven route generates it and the registry has no such @id

The decision reads straight off it: DIFFER is the risk (what publishing changes), would-ADD is the
growth, legacy-only is the coverage gap that publishing does NOT close.

Usage:
    python tools/registry_ownership.py                    # summary across every TAPP
    python tools/registry_ownership.py --verbose          # list the DIFFER defs and what differs
    python tools/registry_ownership.py --registry parameterTemplates
"""
import argparse
import collections
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_tapp as b  # noqa: E402
import schema_path_emitter as spe  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRIES = ("parameterTemplates", "parameterValues",
              "analyteColumns", "reportedPropertyColumns", "channelColumns")


def _def_id(body):
    return str(((body.get("properties") or {}).get("@id") or {}).get("const", ""))


def load_registry(name):
    path = os.path.join(ROOT, "_sources", "registry", name, "schema.yaml")
    if not os.path.exists(path):
        return {}
    doc = yaml.safe_load(open(path, encoding="utf-8")) or {}
    return doc.get("$defs") or {}


def generated(tapps):
    """{registry: {@id: (def key, body, tapp)}} the path-driven route produces, without writing."""
    out = collections.defaultdict(dict)
    failed = []
    for t in tapps:
        try:
            _, regs, _ = spe.build(t)
        except Exception as exc:                      # a TAPP with no sidecar, or a bad path
            failed.append((t, type(exc).__name__))
            continue
        for reg, defs in regs.items():
            for k, v in defs.items():
                out[reg][_def_id(v)] = (k, v, t)
    return out, failed


def body_diff(stored, gen):
    """Which top-level keys / properties differ, as a short human-readable list."""
    out = []
    for k in sorted(set(stored) | set(gen)):
        if stored.get(k) != gen.get(k):
            out.append(k)
    sp, gp = (stored.get("properties") or {}), (gen.get("properties") or {})
    props = [k for k in sorted(set(sp) | set(gp)) if sp.get(k) != gp.get(k)]
    if props:
        out = [o for o in out if o != "properties"] + [f"properties/{p}" for p in props]
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--registry", action="append", help="limit to one registry (repeatable)")
    ap.add_argument("--verbose", action="store_true", help="list the DIFFER defs and what differs")
    args = ap.parse_args()

    tapps = sorted(b.TAPP_CONFIGS)
    gen, failed = generated(tapps)
    if failed:
        print(f"note: {len(failed)} TAPP(s) do not run through the path-driven route "
              f"({', '.join(t for t, _ in failed)}) — their defs count as legacy-only\n")

    names = args.registry or REGISTRIES
    grand = collections.Counter()
    for reg in names:
        stored = load_registry(reg)
        by_id = {_def_id(v): (k, v) for k, v in stored.items()}
        g = gen.get(reg, {})

        agree = differ = 0
        differs = []
        for did, (skey, sbody) in by_id.items():
            if did not in g:
                continue
            _gkey, gbody, tapp = g[did]
            if sbody == gbody:
                agree += 1
            else:
                differ += 1
                differs.append((skey, tapp, body_diff(sbody, gbody)))
        legacy_only = len(by_id) - agree - differ
        would_add = len([d for d in g if d not in by_id])

        for k, v in (("agree", agree), ("DIFFER", differ),
                     ("legacy-only", legacy_only), ("would-ADD", would_add)):
            grand[k] += v

        print(f"{reg:<26s} {len(stored):>4d} defs   "
              f"agree {agree:>4d}   DIFFER {differ:>4d}   "
              f"legacy-only {legacy_only:>4d}   would-ADD {would_add:>4d}")
        if args.verbose and differs:
            for skey, tapp, fields in differs[:25]:
                print(f"      {skey}  [{tapp}]")
                print(f"          differs in: {', '.join(fields) or '(unknown)'}")
            if len(differs) > 25:
                print(f"      … +{len(differs) - 25} more")

    print()
    print(f"TOTAL   agree {grand['agree']}   DIFFER {grand['DIFFER']}   "
          f"legacy-only {grand['legacy-only']}   would-ADD {grand['would-ADD']}")
    print()
    print("DIFFER is what publishing from the path-driven route would overwrite; would-ADD is the")
    print("growth; legacy-only is the coverage gap publishing does NOT close.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
