$schema: https://json-schema.org/draft/2020-12/schema
title: PSFD Instrument Detail
description: Point Spread Function Data with image names and conditions
type: object
properties:
  ada:componentType:
    const: "ada:PSFDTabular"
  'ada:imageName':
    $ref: ../../../../BaseSchema/stringArray/schema.yaml
  'ada:imageViewingConditions':
    type: string
required:
  - ada:componentType
